# Generated by Django 4.1.6 on 2023-04-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Удалить'),
        ),
    ]
